---

# Deployment

kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ service.name }}
  namespace: zgw
  labels:
    k8s-app: {{ service.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: {{ service.name }}
  template:
    metadata:
      name: {{ service.name }}
      labels:
        k8s-app: {{ service.name }}
    spec:
      containers:
      - name: {{ service.name }}
        image: vngr/gemma-zaken-docs:latest
        imagePullPolicy: Always
        resources:
          requests:
            memory: "10Mi"
            cpu: "5m"
          limits:
            memory: "50Mi"
            cpu: "50m"
        readinessProbe:
          httpGet:
            path: /
            port: 80
        livenessProbe:
          httpGet:
            path: /
            port: 80


---

# Service

kind: Service
apiVersion: v1
metadata:
  name: {{ service.name }}
  namespace: zgw
  labels:
    k8s-app: {{ service.name }}
spec:
  selector:
    k8s-app: {{ service.name }}
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
